### ISSUE TITLE
Home page unclickable

### ISSUE THREAD

**Issue by dtinth** [heyfirst/heyfirst.co#32]
Hi @heyfirst. I was surfing the web ring and noticed that your site (https://heyfirst.co/) is unclickable — when you click on the links, nothing happened.

Seems like the graphics you added prevents clicks from going through. Maybe add `pointer-events-none`?

By the way, I plan to add RSS feed support to the webring soon. If you add one, your latest post will be shown from the webring’s home page.

**Comment by heyfirst** [comment]
Thank youuuuuu P' @dtinth let me fix themm 🙇🏻🙇🏻🙇🏻🙇🏻

**Comment by heyfirst** [comment]
@dtinth I found that and fixed it 🙇🏻 

The problem come form `pnpm` which is quite strict as it's automatically install the peerDependencies (https://github.com/pnpm/pnpm/issues/827#issuecomment-311135922 comment from maintainer)

then the @babel/core was missing. That cause the styled-jsx can not even build. 😂  That's why my `index: -1` css does not applied to the component.

Shame of me~

**Comment by heyfirst** [comment]
The RSS feed (https://github.com/heyfirst/heyfirst.co/issues/34) will be available soon kub 🥳  hope I can finish before you implement it on webring.

btw, I'm happy to help to contribute as well kubbbbbbb. yah

**Comment by dtinth** [comment]
Thanks! About RSS, check out this comment krubb https://github.com/wonderfulsoftware/webring/pull/82#issuecomment-1023593743

Cheers~
